DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = ""
DB_NAME = "triplew"

CLAVE_SECRETA = "OLZMs9zmZ0zCJUtLBT4r56bwvTAEI7HxSWLQ0DqP9XDrAUv71ZA4jMYFfgGcnFfVz5IYMqq5vRQG0g6ahMz7QA"
ALGORITMO = "HS256"
MINUTOS_EXPIRACION_TOKEN = 60